version: "3"
services:

  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.r18i.me'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.r18i.me:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.r18i.me`)"
        
networks:
  proxy:
    external: true
