version: '3.3'
services:
    httpd:
        container_name: apache-server
        ports:
            - '8080:80'
        volumes:
            - '$PWD/htdocs/:/usr/local/apache2/htdocs/'
        image: 'httpd:2.4'
        networks:
            - proxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.apache-secure.entrypoints=websecure"
            - "traefik.http.routers.apache-secure.rule=Host(`r18i.me`)"

networks:
  proxy:
    external: true
