---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - $PWD/assets/:/www/assets
    ports:
      - 8092:8080
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homer-secure.entrypoints=websecure"
      - "traefik.http.routers.homer-secure.rule=Host(`home.r18i.me`)"


networks:
  proxy:
    external: true
